In [1]:
import numpy as np

In [13]:
escalar = 5.679
vector  = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([
    [[1,2,3,10],[4,5,6,20],[6,7,8,30]],
    [[11,12,13,40],[14,15,16,50],[17,18,19,60]],
    [[21,22,23,70],[24,25,26,80],[27,28,29,90]]
])

In [14]:
print(escalar)

5.679


In [15]:
matriz.shape

(2, 2)

In [16]:
tensor.shape

(3, 3, 4)

In [17]:
vector_t = vector.T
print(vector_t)

[1 2 3]


In [18]:
matriz_t = matriz.T
print(matriz_t)

[[1 3]
 [2 4]]


In [20]:
tensor_t = tensor.T
tensor_t

array([[[ 1, 11, 21],
        [ 4, 14, 24],
        [ 6, 17, 27]],

       [[ 2, 12, 22],
        [ 5, 15, 25],
        [ 7, 18, 28]],

       [[ 3, 13, 23],
        [ 6, 16, 26],
        [ 8, 19, 29]],

       [[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]]])

In [21]:
tensor

array([[[ 1,  2,  3, 10],
        [ 4,  5,  6, 20],
        [ 6,  7,  8, 30]],

       [[11, 12, 13, 40],
        [14, 15, 16, 50],
        [17, 18, 19, 60]],

       [[21, 22, 23, 70],
        [24, 25, 26, 80],
        [27, 28, 29, 90]]])

In [22]:
# Video 7
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [23]:
A = matriz.T + vector

In [24]:
A

array([[ 4,  7, 10],
       [ 5,  8, 11]])