In [1]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [5]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [6]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [7]:
v1 = np.array([1,1,1,1])
print(v1)

[1 1 1 1]


In [8]:
print(A.dot(v1.T))

[2 3 4 5]


In [9]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [10]:
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [12]:
np.linalg.norm([1/2,1/2,1/2,1/2])

1.0

In [13]:
2*3*4*5

120

In [14]:
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [15]:
A+2

array([[4, 2, 2, 2],
       [2, 5, 2, 2],
       [2, 2, 6, 2],
       [2, 2, 2, 7]])