In [1]:
import numpy as np
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [2]:
A = matriz *vector

In [3]:
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

In [5]:
B = matriz.dot(vector)
B

array([ 8, 18, 28])

In [7]:
C = np.dot(matriz, vector)
B == C

array([ True,  True,  True])

In [8]:
# Productor interno

In [9]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [10]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136]])

In [11]:
B.dot(A)

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)