In [4]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [7]:
data = pd.DataFrame(iris.data)
data.columns = iris.feature_names
data["target"] = iris.target

In [8]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
data["name_t"] = data["target"].map({0:"setosa", 1:"versicolor",2:"virginica"})

In [11]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  name_t  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [14]:
from sklearn.model_selection import train_test_split

In [20]:
target = ["target","name_t"]
desc = list(set(list(data.columns)) - set(target))

In [21]:
desc

['sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)',
 'sepal length (cm)']

In [22]:
X = data[desc].values
y = data["target"].values

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=40)

In [24]:
from sklearn.tree import DecisionTreeRegressor

In [25]:
reg_1 = DecisionTreeRegressor(max_depth=4)
reg_1.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=4)

In [26]:
predict_train = reg_1.predict(X_train)
predict_test = reg_1.predict(X_test)

In [27]:
from sklearn.metrics import classification_report, confusion_matrix


In [29]:
print(classification_report(y_test,predict_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        15

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [30]:
print(confusion_matrix(y_test,predict_test))

[[16  0  0]
 [ 0 14  0]
 [ 0  0 15]]
