In [31]:
import torch
import numpy as np
import pandas as pd

# Trabajando con Tensores
------

In [2]:
torch.__version__

'1.5.1+cu101'

In [3]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [4]:
tensor_b = torch.Tensor(2,2)

In [5]:
tensor_b

tensor([[1.5796e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])

In [6]:
tensor_b.uniform_(0,1)

tensor([[0.6245, 0.1181],
        [0.1595, 0.8447]])

In [7]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.1175, 0.0586],
        [0.8022, 0.7509]])

In [8]:
result = tensor_b+ tensor_a

In [10]:
result.shape

torch.Size([2, 2])

In [11]:
reshaped = result.view(4,1)
reshaped

tensor([[1.6245],
        [1.1181],
        [1.1595],
        [1.8447]])

In [12]:
points = torch.tensor([[1.0,2.0],[3.0,4.0]])
points

tensor([[1., 2.],
        [3., 4.]])

In [14]:
points[0][1] = 2.5
points

tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])

In [15]:
points.storage()

 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [17]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [19]:
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [21]:
tensor_x = torch.tensor([1,2,3,4])
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [22]:
import numpy as np

numpyArray = np.random.rand(2,2)

In [25]:
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[0.0675, 0.9760],
        [0.6687, 0.4807]], dtype=torch.float64)

#  Representar datos con tensores 
-----

In [28]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[0.0675, 0.9760],
        [0.6687, 0.4807]], dtype=torch.float64)
tensor(0.5482, dtype=torch.float64)
tensor([0.3681, 0.7283], dtype=torch.float64)
tensor([0.5217, 0.5747], dtype=torch.float64)


In [29]:
torch.save(from_numpy, "tensor.t")

In [30]:
load = torch.load("tensor.t")
load

tensor([[0.0675, 0.9760],
        [0.6687, 0.4807]], dtype=torch.float64)

In [ ]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
df = pd.read_csv(url)
df.head()

In [ ]:
df.columns

In [42]:
subset = df[["Overall","Age",'International Reputation', 'Weak Foot','Skill Moves']].dropna(axis=0, how="any")
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [43]:
data = players[:,1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [44]:
target = players[:,0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [45]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [48]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [49]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [54]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target,85)]
notSoGood =  data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averangeMean = torch.mean(average, dim = 0)
notSoGoodMean = torch.mean(notSoGood, dim = 0)

goodMean, averangeMean, notSoGoodMean

for i, args in enumerate(zip(columns, goodMean, averangeMean, notSoGoodMean)):
  print("{:25} {:6.2f} {:6.2f} {:6.2f}".format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
