In [1]:
%matplotlib inline
import numpy as np

In [3]:
A = np.array([[3,2],[4,1]])
print(A)

[[3 2]
 [4 1]]


In [4]:
autovalores, autovectores = np.linalg.eig(A)

In [5]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [7]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
A_calc

array([[3., 2.],
       [4., 1.]])

In [8]:
A = np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


In [9]:
print(A==A.T)

[[ True  True]
 [ True  True]]
