In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [3]:
U, D, V = np.linalg.svd(A)
print("U \n", U)
print("D \n", D)
print("V \n", V)

U 
 [[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D 
 [19.40321383  0.71783924]
V 
 [[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [4]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print("Valores a remplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a remplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [6]:
print("Valores que pondemos en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que pondemos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [7]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [8]:
A_pse = V.T.dot(D_pse).dot(U.T)
A_pse

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [9]:
A_pse_cal = np.linalg.pinv(A)
print(A_pse_cal)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [10]:
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


In [11]:
np.set_printoptions(suppress=False)
print(A_pse.dot(A))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


In [19]:
B = np.array([[1 ,2],[3 ,4],[5, 6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
U, D, V = np.linalg.svd(B)
print("U \n", U)
print("D \n", D)
print("V \n", V)

U 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
D 
 [9.52551809 0.51430058]
V 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
