In [4]:
import numpy as np
import pandas as pd

In [6]:
pd.options.display.float_format = '{:.2f}'.format

In [11]:
np.set_printoptions(precision=1)

In [15]:
x1 = np.random.rand(2,5)*10
x1

array([[9.1, 9.3, 9.3, 1.4, 9.6],
       [3.2, 6.5, 5.8, 7.2, 2. ]])

In [16]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.8, -0.4, -0.4, -0.7, -0.1],
       [-0.5, -0.6, -0.9, -0. , -0.2]])

In [17]:
np.concatenate([x1,x2])

array([[ 9.1,  9.3,  9.3,  1.4,  9.6],
       [ 3.2,  6.5,  5.8,  7.2,  2. ],
       [-0.8, -0.4, -0.4, -0.7, -0.1],
       [-0.5, -0.6, -0.9, -0. , -0.2]])

In [18]:
np.concatenate([x1,x2]).shape

(4, 5)

In [19]:
np.concatenate([x1,x2], axis=1)

array([[ 9.1,  9.3,  9.3,  1.4,  9.6, -0.8, -0.4, -0.4, -0.7, -0.1],
       [ 3.2,  6.5,  5.8,  7.2,  2. , -0.5, -0.6, -0.9, -0. , -0.2]])

In [20]:
np.concatenate([x1,x2], axis=1).shape

(2, 10)

In [34]:
s1 = pd.Series(x1[1], index=['a','b','c','d','e'])
s1

a   3.22
b   6.51
c   5.81
d   7.16
e   2.04
dtype: float64

In [35]:
s2 = pd.Series(x1[0], index=['c','d','e','f','g'])
s2

c   9.09
d   9.31
e   9.35
f   1.39
g   9.56
dtype: float64

In [36]:
pd.concat([s1,s2])

a   3.22
b   6.51
c   5.81
d   7.16
e   2.04
c   9.09
d   9.31
e   9.35
f   1.39
g   9.56
dtype: float64

In [37]:
pd.concat([s1,s2], axis=1)

0    1
a 3.22  nan
b 6.51  nan
c 5.81 9.09
d 7.16 9.31
e 2.04 9.35
f  nan 1.39
g  nan 9.56

In [39]:
s1.reset_index(drop=True)

0   3.22
1   6.51
2   5.81
3   7.16
4   2.04
dtype: float64

In [40]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0    1
0 3.22 9.09
1 6.51 9.31
2 5.81 9.35
3 7.16 1.39
4 2.04 9.56

In [42]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 8.25 6.49
1 6.65 5.66
2 4.66 3.86

In [44]:
df2 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'], index = [2,3,4])
df2

a    b
2 0.79 2.47
3 7.03 5.18
4 2.87 9.90

In [45]:
pd.concat([df1,df2])

a    b
0 8.25 6.49
1 6.65 5.66
2 4.66 3.86
2 0.79 2.47
3 7.03 5.18
4 2.87 9.90

In [46]:
pd.concat([df1,df2], axis=1)

a    b    a    b
0 8.25 6.49  nan  nan
1 6.65 5.66  nan  nan
2 4.66 3.86 0.79 2.47
3  nan  nan 7.03 5.18
4  nan  nan 2.87 9.90

In [47]:
pd.concat([df1,df2], axis=1,join="inner")

a    b    a    b
2 4.66 3.86 0.79 2.47

In [48]:
pd.concat([
    df1.reset_index(drop=True),
    df2.reset_index(drop=True)
], axis=1)

a    b    a    b
0 8.25 6.49 0.79 2.47
1 6.65 5.66 7.03 5.18
2 4.66 3.86 2.87 9.90

In [49]:
df1.append(df2).append(df2)

a    b
0 8.25 6.49
1 6.65 5.66
2 4.66 3.86
2 0.79 2.47
3 7.03 5.18
4 2.87 9.90
2 0.79 2.47
3 7.03 5.18
4 2.87 9.90

In [50]:
df1.T

0    1    2
a 8.25 6.65 4.66
b 6.49 5.66 3.86

In [51]:
df1.T.append(df2.T).T

a    b    a    b
0 8.25 6.49  nan  nan
1 6.65 5.66  nan  nan
2 4.66 3.86 0.79 2.47
3  nan  nan 7.03 5.18
4  nan  nan 2.87 9.90